name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mkdir build && mkdir firmware && docker run --rm -i -v$GITHUB_WORKSPACE:/home/espbuilder/project darlanalves/homebots-sdk:latest
